

# Site Settings
title: 						"Sassigeeks"
email: 						"jus@envyserve.com"
description: 				"I just want to create beautiful things even if nobody cares."
baseurl: 					""
url: 						"http://sassigeeks.com"
logourl: 					"/assets/img/bloglogo.jpg"		
fa-logo: 					"fa-bookmark-o"
paginate: 					5


# Author Settings
author_name: 				"Jus Hay"
author_url: 				"http://sassigeeks.com"
author_bio: 				"Lorem Ipsum"
author_email: 				"jus@envyserve.com"
author_image: 				"/assets/img/authorimage.jpg"


# Social Settings
twitter_url: 				"http://twitter.com/sassigeeks"
github_url:  				"http://github.com/sassigeeks"
youtube_url:  				"http://youtube.com/sassigeeks"
dribbble_url:  				"http://dribbble.com/sassigeeks"
googleplus_url: 			"http://google.com/plus"
instagram_url:  			"http://instagram.com/sassigeeks"
pinterest_url:  			"http://pinterest.com/sassigeeks"


# Theme Settings
theme_disqus_shortname: 	"ecko"
theme_google_comments: 		false
theme_analytics_id: 		""
theme_analytics_domain: 	"sassigeeks.com"
theme_reading_time: 		true
theme_autoload_comments: 	false
theme_always_show_nav: 		true


# SASS Settings
# DO NOT MODIFY
sass:
 sass_dir: "assets/css/"
 style: :compressed


# Build Settings
markdown: 					kramdown
permalink: 					pretty

